#!/bin/bash
# Created by Victoria Fuller
# Date: 14/06/2025

# Script Name:
# 1_combine_sv_vcf.sh
# Description: Combines structural VCF files generated by Manta

# How to run:
# Log in to CYNAPSE using magic link
# Start interactive session and open terminal
# Mount annotated structural variant vcf files into session data
# sample202.manta.diploid_sv_VEP.ann.vcf.gz, sample252.manta.diploid_sv_VEP.ann.vcf.gz, 
# sample301.manta.diploid_sv_VEP.ann.vcf.gz, sample302.manta.diploid_sv_VEP.ann.vcf.gz, sample303.manta.diploid_sv_VEP.ann.vcf.gz
# Run: bash 1_combine_sv_vcf.sh

set -euo pipefail

# Define the current step for file names
current_step="combine_sv"

# Define directories
data_input_dir="/home/jovyan/session_data/mounted-data-readonly/"
data_output_dir="/home/jovyan/session_data/output-data/"

# Define vcf files
unaffected_f_relative="sample202.manta.diploid_sv_VEP.ann.vcf.gz"
father="sample252.manta.diploid_sv_VEP.ann.vcf.gz"
proband="sample301.manta.diploid_sv_VEP.ann.vcf.gz"
f_sibling="sample302.manta.diploid_sv_VEP.ann.vcf.gz"
m_sibling="sample303.manta.diploid_sv_VEP.ann.vcf.gz"


# Accept input files
vcf_input_files=("${unaffected_f_relative}" "${father}" "${proband}" "${f_sibling}" "${m_sibling}")

# Ensure the output directory exists
mkdir -p "${data_output_dir}"

# Extract base name for output file name
vcf_output_file="${data_output_dir}/merged.manta.diploid_sv_VEP.ann.vcf.gz"

# Check the input file exists
if [[ ! -f "${vcf_input_files}" ]]; then
  echo "ERROR: Input VCF file not found at ${vcf_input_files}"
  exit 1
fi

# Log tool version
echo "Using bcftools version:"
bcftools --version

# Run merge command
# Merges VCF files from individual samples to create a multi-sample VCF
echo "Merging structural variant VCF files..."
bcftools merge "${unaffected_f_relative}" "${father}" "${proband}" "${f_sibling}" "${m_sibling}" \
  --output "${vcf_output_file}" \
  --output-type z

# Index output VCF
tabix -p vcf "${vcf_output_file}"

echo "Merged VCF written to ${vcf_output_file}"