#!/bin/bash
# Created by Victoria Fuller
# Date: 30/10/2025

# Script Name:
# combine_sv_vcf.sh
# Description: Combines structural VCF files generated by Manta

# How to run:
# Log in to CYNAPSE using magic link
# Start interactive session and open terminal
# Mount annotated vcf files into session data
# Run: bash combine_sv_vcf.sh

set -euo pipefail

# Define the current step for file names
current_step="combine_sv"

# Define directories
data_input_dir="/home/jovyan/session_data/mounted-data-readonly/"
data_output_dir="/home/jovyan/session_data/output-data/"

# Define vcf files
vcf_input_files=("${data_input_dir}"/*.manta.diploid_sv_VEP.ann.vcf.gz)

# Ensure the output directory exists
mkdir -p "${data_output_dir}"

# Extract base name for output file name
vcf_output_file="${data_output_dir}/merged.manta.diploid_sv_VEP.ann.vcf.gz"

# Check the input file exists
if [[ ${#vcf_input_files[@]} -eq 0 ]]; then
  echo "ERROR: Input VCF files not found"
  exit 1
fi

# Log tool version
echo "Using bcftools version:"
bcftools --version

# Run merge command
# Merges VCF files from individual samples to create a multi-sample VCF
echo "Merging structural variant VCF files..."
bcftools merge "${vcf_input_files[@]}" \
    --output "${vcf_output_file}" \
    --output-type z

# Index output VCF
tabix -p vcf "${vcf_output_file}"

echo "Merged VCF written to ${vcf_output_file}"